name: Get Citation Data

on: 
 page_build: 
 schedule:
  - cron:  '0 0 */7 * *'  # 每7天的午夜（UTC时间）触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
        python3 main.py
        git config --local user.name "${GITHUB_ACTOR}"
        git clone -b google-scholar-stats https://${GITHUB_ACTOR}:${{ secrets.PERSONAL_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git stats-update
        mv ./results/* ./stats-update/
        cd stats-update
        git add *.json
        git commit -m "Updated Citation Data"
        git push --force origin google-scholar-stats
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
